menu:
- {name: 'publications', url: '/publications'}
- {name: 'resources', url: '/resources'}

courses:
- {name: "Discrete Math (TA) (link to Gil Cohen's site, Hebrew)", url: 'https://www.gilcohen.org/bdida'}

social:
- {icon: 'github', link: 'https://github.com/yoavGaltzur'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yoav-galtzur/'}
- {icon: 'dblp', link: "https://dblp.org/pid/357/3063.html"}

talks:
- {name: "Fair Division via Resource Augmentation at the Israeli AGT Day 2025", url: "https://www.youtube.com/watch?v=Qa0_j70uVYM"}

publications:
- {name: "Budget-Feasible Contracts", url: "https://arxiv.org/abs/2504.01773", coauthors: "Michal Feldman, Tomasz Ponitka and Maya Schlesinger", venue: "under submission"}
- {name: "Fair Division via Resource Augmentation", url: "https://arxiv.org/abs/2502.09377", coauthors: "Hannaneh Akrami, Alon Eden, Michal Feldman and Amos Fiat", venue: "under submission"}
- {name: "The Query Complexity of Contracts", url: "https://arxiv.org/abs/2403.09794", coauthors: "Paul Dütting, Michal Feldman and Aviad Rubinstein", venue: "under submission"}
- {name: "Combinatorial Contracts Beyond Gross Substitutes", url: "https://arxiv.org/abs/2309.10766", coauthors: "Paul Dütting and Michal Feldman", venue: "SODA 2024"}

updates:
- {content: "A new arXiv upload: 'Budget-Feasible Contracts'", date: "April 2025"}
- {content: "I gave a talk at the Israeli AGT Day", date: "March 2025"}
- {content: "A new arXiv upload: 'Fair Division via Resource Augmentation'", date: "February 2025"}
- {content: "A new arXiv upload: 'The Query Complexity of Contracts'", date: "March 2024"}
- {content: "Our paper 'Combinatorial Contracts Beyond Gross Substitutes' was accepted to SODA 2024!", date: "October 2023"}

