menu:
# - {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'resources', url: '/resources'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}


courses:
- {name: "Discrete Math (TA) (link to Gil Cohen's site, Hebrew)", url: 'https://www.gilcohen.org/bdida'}
# - {name: 'Discrete Math (TA)', url: 'https://www.gilcohen.org/bdida'}

social:
- {icon: 'github', link: 'https://github.com/yoavGaltzur'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yoav-galtzur/'}

contacts:
- {name: 'Yoav Gal-Tzur', title: 'PhD Student', department: 'Computer Science', institution: 'Tel-Aviv University', email: 'yoavgaltzur@mail.tau.ac.il', image: 'assets/img/contact.jpg'}
# - {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}

talks:
- {name: "Fair Division via Resource Augmentation at the Israeli AGT Day 2025", url: "https://www.youtube.com/watch?v=Qa0_j70uVYM"}
